name = "sweethopebakeryy-js"
pages_build_output_dir = "src"
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "kv-db"
id = "484eac01223645b5a7d53de5ae5d2917"

[vars]
DEBUG_ERRORS = "false"
PAGES_PURGE_DEBUG = "true"
PAGES_PURGE_AFTER_DEPLOY = "true"
CLOUDFLARE_ZONE_ID = "dcb06d98570b7699bebf9bab3fc876fb"
PAGES_PURGE_DELAY_MS = "10000"